.TH "Board" 3 "Sat Oct 26 2019" "Gomoku" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Board\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoard\fP (size_t size)"
.br
.ti -1c
.RI "\fB~Board\fP ()=default"
.br
.ti -1c
.RI "\fBBoard\fP ()=default"
.br
.ti -1c
.RI "void \fBaddCoordinates\fP (const int &player, std::pair< int, int > pos)"
.br
.ti -1c
.RI "const std::vector< std::vector< int > > & \fBgetBoard\fP ()"
.br
.ti -1c
.RI "size_t \fBgetSize\fP () const"
.br
.ti -1c
.RI "bool \fBisEmpty\fP ()"
.br
.ti -1c
.RI "int \fBgetCell\fP (int, int)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Board::Board (size_t size)"

.SS "Board::~Board ()\fC [default]\fP"

.SS "Board::Board ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Board::addCoordinates (const int & player, std::pair< int, int > pos)"

.SS "const std::vector< std::vector< int > > & Board::getBoard ()"

.SS "int Board::getCell (int x, int y)"

.SS "size_t Board::getSize () const"

.SS "bool Board::isEmpty ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gomoku from the source code\&.
