.TH "src Directory Reference" 3 "Sat Oct 26 2019" "Gomoku" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAI\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAI\&.hpp\fP"
.br
.ti -1c
.RI "file \fBBoard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBoard\&.hpp\fP"
.br
.ti -1c
.RI "file \fBGomoku\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGomoku\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTree\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTree\&.hpp\fP"
.br
.in -1c
