.TH "src/Gomoku.hpp" 3 "Sat Oct 26 2019" "Gomoku" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Gomoku.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Board\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'AI\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandManager\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__GOMOKU_HPP__\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __GOMOKU_HPP__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Gomoku from the source code\&.
